# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# --------------------------
description: >- # used by seo meta and the atom feed
  Personal website of Steffen Mads Lyng
url: "https://lyng.dev"
author: Steffen Mads Lyng # change to your full name
github:
  username: lyng-dev # change to your github username
social:
  name: Steffen Mads Lyng # it will shows as the copyright owner in Footer
  email: sm@lyng.dev # change to your email address
  links:
    - https://github.com/lyng-dev # change to your github homepage
    - https://www.linkedin.com/in/smsl
google_site_verification: google_meta_tag_verification # change to your verification string
baseurl: ""
timezone: Europe/Copenhagen
google_analytics:
  id: "187517553" # Fill with your Google Analytics ID
  pv:
    # The Google Analytics pageviews switch.
    # DO NOT enable it unless you know how to deploy the Google Analytics superProxy.
    enabled: false
    # the next options only valid when `google_analytics.pv` is enabled.
    proxy_url: ""
    proxy_endpoint: ""
    cache: false # pv data local cache, good for the users from GFW area.
theme_mode: dark
img_cdn: ""
avatar: /assets/img/logo.png
toc: true
paginate: 10
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
permalink: /posts/:title/

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      breadcrumb:
        - label: Posts
          url: /
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: index.html
    values:
      breadcrumb:
        - label: Posts
  - scope:
      path: tags
    values:
      breadcrumb:
        - label: Home
          url: /
        - label: Tags
          url: /tabs/tags/
  - scope:
      path: categories
    values:
      breadcrumb:
        - label: Home
          url: /
        - label: Categories
          url: /tabs/categories/
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      dynamic_title: true # Hide title in mobile screens.
      breadcrumb:
        - label: Home
          url: /

sass:
  sass_dir: /assets/css
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - vendor
  - Gemfile.lock
  - Gemfile
  - tools
  - docs
  - README.md
  - LICENSE

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
